In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('all_data.csv')
df.head(10)

  Country  Year  Life expectancy at birth (years)           GDP
0   Chile  2000                              77.3  7.786093e+10
1   Chile  2001                              77.3  7.097992e+10
2   Chile  2002                              77.8  6.973681e+10
3   Chile  2003                              77.9  7.564346e+10
4   Chile  2004                              78.0  9.921039e+10
5   Chile  2005                              78.4  1.229650e+11
6   Chile  2006                              78.9  1.547880e+11
7   Chile  2007                              78.9  1.736060e+11
8   Chile  2008                              79.6  1.796380e+11
9   Chile  2009                              79.3  1.723890e+11

In [4]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 4 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country                           96 non-null     str
 1   Year                              96 non-null     int64
 2   Life expectancy at birth (years)  96 non-null     float64
 3   GDP                               96 non-null     float64
dtypes: float64(2), int64(1), str(1)
memory usage: 4.0 KB

              Year  Life expectancy at birth (years)           GDP
count    96.000000                         96.000000  9.600000e+01
mean   2007.500000                         72.789583  3.880499e+12
std       4.633971                         10.672882  5.197561e+12
min    2000.000000                         44.300000  4.415703e+09
25%    2003.750000                         74.475000  1.733018e+11
50%    2007.500000                         76.750000  1.280220e+12
75%    2011.250000                         78.900000  4.067510e+12
max    2015.000000                         81.000000  1.810000e+13

In [5]:
df.isnull().sum()

Country                             0
Year                                0
Life expectancy at birth (years)    0
GDP                                 0
dtype: int64

In [7]:
df['GDP_Billions'] = df['GDP']/ 1e9

In [8]:
print(df.head(10))

  Country  Year  Life expectancy at birth (years)           GDP  GDP_Billions
0   Chile  2000                              77.3  7.786093e+10     77.860932
1   Chile  2001                              77.3  7.097992e+10     70.979924
2   Chile  2002                              77.8  6.973681e+10     69.736811
3   Chile  2003                              77.9  7.564346e+10     75.643460
4   Chile  2004                              78.0  9.921039e+10     99.210393
5   Chile  2005                              78.4  1.229650e+11    122.965000
6   Chile  2006                              78.9  1.547880e+11    154.788000
7   Chile  2007                              78.9  1.736060e+11    173.606000
8   Chile  2008                              79.6  1.796380e+11    179.638000
9   Chile  2009                              79.3  1.723890e+11    172.389000

In [10]:
print(df.duplicated().sum())

0

In [11]:
df.Country.unique()

<ArrowStringArray>
['Chile', 'China', 'Germany', 'Mexico', 'United States of America',
 'Zimbabwe']
Length: 6, dtype: str